# Generated by Django 4.2 on 2023-04-27 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fakultet', '0001_initial'),
        ('amaliyot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amaliyot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amaliyot.amaliyot')),
                ('fakultet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fakultet.fakultetlar')),
            ],
        ),
    ]
