# Generated by Django 4.2.1 on 2023-05-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='yonalish',
        ),
        migrations.AddField(
            model_name='pdf',
            name='korxona_nomi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pdf',
            name='talaba_fakulteti',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pdf',
            name='talaba_nomer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pdf',
            name='talaba_yonalishi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='amaliyot_boshlanishi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='amaliyot_buyruq_raqami',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='amaliyot_joyi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='amaliyot_manzili',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='amaliyot_rahbari',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='amaliyot_tugashi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='amaliyot_turi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='biriktirilgan_rahbar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='shartnoma_raqami',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='talaba_f_i_sh',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='talaba_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='talaba_kurs',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='talaba_manzil',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
