# Generated by Django 4.2.1 on 2023-05-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='amaliyot_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='talaba_id',
            field=models.CharField(max_length=100),
        ),
    ]
