# Generated by Django 4.2.2 on 2023-06-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_remove_pdf_yonalish_pdf_korxona_nomi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('rasm', models.FileField(upload_to='code')),
            ],
        ),
    ]
