# Generated by Django 4.2.2 on 2023-06-13 04:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0003_rasm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rasm',
            old_name='nomi',
            new_name='link',
        ),
        migrations.AddField(
            model_name='rasm',
            name='user_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rasm',
            name='rasm',
            field=models.FileField(upload_to='code/'),
        ),
    ]
