# Generated by Django 4.2.1 on 2023-06-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0004_rename_nomi_rasm_link_rasm_user_id_alter_rasm_rasm'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='derektor_nomer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='rasm',
            name='rasm',
            field=models.ImageField(upload_to='code/'),
        ),
    ]
