# Generated by Django 4.2 on 2023-04-25 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0004_remove_ish_admin_remove_oliy_yurt_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amaliyot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muassasa', models.CharField(max_length=200)),
                ('d_ism', models.CharField(max_length=100)),
                ('d_nomeri', models.CharField(max_length=100)),
                ('a_rahbari', models.CharField(max_length=100)),
                ('o_a_rahbari', models.CharField(max_length=100)),
                ('a_turi', models.CharField(max_length=100)),
                ('b_sana', models.CharField(max_length=100)),
                ('t_sana', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fakultet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fakultet', models.CharField(max_length=100)),
                ('kafedra', models.CharField(max_length=100)),
                ('guruh', models.CharField(max_length=100)),
                ('kurs', models.CharField(max_length=100)),
                ('talim_turi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Viloyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viloyat', models.CharField(max_length=100)),
                ('tuman', models.CharField(max_length=100)),
                ('mfy', models.CharField(max_length=100)),
                ('kocha_uy', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Ish',
        ),
        migrations.DeleteModel(
            name='Oliy_yurt',
        ),
        migrations.AddField(
            model_name='amaliyot',
            name='viloyat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf.viloyat'),
        ),
    ]
