# Generated by Django 4.2.2 on 2023-09-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0005_pdf_derektor_nomer_alter_rasm_rasm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='amaliyot_joyi',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='amaliyot_manzili',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
