# Generated by Django 4.2.2 on 2024-02-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0006_alter_pdf_amaliyot_joyi_alter_pdf_amaliyot_manzili'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='amaliyot_boshlanishi',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='amaliyot_buyruq_raqami',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='amaliyot_rahbari',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='amaliyot_tugashi',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='amaliyot_turi',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='biriktirilgan_rahbar',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='talaba_f_i_sh',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='talaba_kurs',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='talaba_manzil',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='talaba_shifr',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='talaba_yonalishi',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
