# Generated by Django 4.2 on 2023-04-25 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0007_alter_pdf_fakultet_id_alter_pdf_talaba_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='fakultet_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pdf.fakultet'),
        ),
    ]
