# Generated by Django 4.2 on 2023-04-26 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amaliyot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fakultet', '0001_initial'),
        ('pdf', '0009_alter_pdf_amaliyot_id_alter_pdf_talaba_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='amaliyot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amaliyot.amaliyot'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='fakultet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fakultet.fakultetlar'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='talaba_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Amaliyot',
        ),
        migrations.DeleteModel(
            name='Fakultet',
        ),
        migrations.DeleteModel(
            name='Viloyat',
        ),
    ]
