# Generated by Django 4.1.6 on 2023-02-15 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='familya',
            new_name='familya_i',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='ism',
            new_name='ism_i',
        ),
    ]
