# Generated by Django 4.2 on 2023-04-25 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_familya_user_familya_i_rename_ism_user_ism_i'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='familya_i',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ism_i',
        ),
        migrations.RemoveField(
            model_name='user',
            name='k_yil',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kocha',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shahar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sharif_i',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telefon',
        ),
        migrations.RemoveField(
            model_name='user',
            name='uy_nomer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='viloyat',
        ),
        migrations.RemoveField(
            model_name='user',
            name='yonalish',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='t_nomer',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='sharif',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='t_yil',
            field=models.CharField(max_length=100),
        ),
    ]
