# Generated by Django 4.2 on 2023-04-27 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuman', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Viloyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viloyat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Viloyatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfy', models.CharField(max_length=100)),
                ('kocha_uy', models.CharField(max_length=200)),
                ('tumam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viloyat.tuman')),
                ('viloyat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viloyat.viloyat')),
            ],
        ),
    ]
