# Generated by Django 4.2.1 on 2023-05-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amaliyot', '0006_alter_amaliyot_talaba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amaliyot',
            name='talaba',
            field=models.IntegerField(),
        ),
    ]
